#pragma once

#include <array>
#include <cstdint>
#include <format>
#include <string>
#include <string_view>

#if defined(_WIN32)
#include <windows.h>
#endif

namespace OST::ExtractTickets {

enum class Language : size_t {
    English = 0,
    Chinese = 1,
    Spanish = 2
};

enum class MsgKey : size_t {
    // Lua Comments
    LuaHeader = 0,
    LuaBaseGame,
    LuaBaseManifests,
    LuaManifestMissing,
    LuaOwnedDlcs,
    LuaDlcDepotMissing,
    LuaDlcManifests,
    LuaAppTicket,
    LuaAppTicketMissing,
    LuaETicket,
    LuaETicketNote,

    // CSV Headers
    CsvIndex,
    CsvAppId,
    CsvName,
    CsvType,
    CsvOwned,
    CsvShared,

    // TUI Level 1
    L1HeaderTagLocal,
    L1HeaderTagNoSteam,
    L1BoxTitle,
    L1Welcome,
    L1LocalDesc,
    L1NoSteamNotice,
    L1InputPrompt,
    L1Footer,

    // TUI Level 2
    L2HeaderTagAccounts,
    L2BoxTitle,
    L2Subtitle,
    L2ActionLogin,
    L2ActionWipe,
    L2TipLogin,
    L2TipCached,
    L2TipWipe,
    L2Footer,

    // TUI Level 3
    L3HeaderAccount,
    L3HeaderPage,
    L3BoxTitle,
    L3ColIndex,
    L3ColAppId,
    L3ColName,
    L3ColStatus,
    L3StatusShared,
    L3StatusReady,
    L3QuickInputPrompt,
    L3Footer,

    // Modals & General
    BtnClose,
    BtnYes,
    BtnNo,
    HintInputEnterEsc,
    ExtractingTitle,
    ExtractingLocalMsg,
    ExtractingOnlineTitle,
    ExtractingOnlineMsg1,
    ExtractingOnlineMsg2,
    ExtractSuccessTitle,
    ExtractSuccessMsg,
    ExtractSuccessDetail,
    ExtractWarnTitle,
    ExtractWarnMsg,
    BatchExtractTitle,
    BatchAbortedTitle,
    BatchAbortedMsg,
    BatchAbortedDetail,
    BatchSuccessTitle,
    BatchSuccessMsg,
    BatchSuccessDetail,
    DelAccountTitle,
    DelAccountMsg,
    DelAccountDetail,
    WipeAllTitle,
    WipeAllMsg,
    WipeAllDetail,
    LoginFailedTitle,
    LoginFailedDefaultMsg,
    LoginFailedDetail,
    InvalidAppId,
    GuardMobileTitle,
    GuardMobilePrompt,
    GuardEmailTitle,
    GuardEmailPrompt,
    GuardDeviceTitle,
    GuardDevicePrompt,
    GuardDeviceDetail,
    ErrNoSavedAccounts,
    ErrNoSavedAccountsTip,
    ErrAccountNotFound,
    ErrAccountListTip,
    ErrAuthTimeoutOrCancelled,
    ErrUserCancelledInput,
    ErrUserCancelledDevice,
    ErrUserCancelledPwd,
    ErrUserCancelledPoll,
    ErrRsaKeyFailed,
    ErrAuthSessionFailed,
    ConnectingTitle,
    ConnectingGatewayMsg,
    ConnectingRefreshingMsg,
    ConnectingFailedTitle,
    ConnectingFailedMsg,
    ConnectingFailedDetail,
    SyncingGamesMsg,
    NoGamesFoundTitle,
    NoGamesFoundMsg,
    NoGamesFoundDetail,
    CliExtractAttempting,
    CliExtractUsing,
    CliExtractTokenExpired,
    CliExtractLoginSuccess,
    CliExtractFallbackBase,
    CliExtractSuccess,
    CliExtractWarn,
    CliExtractFailedAll,
    CliExtractFailedAllTip,
    TimestampUnknown,
    L1NavTitle,
    L1NavOnline,
    L1NavExit,
    L1InputTip,
    NoSteamConfirmTitle,
    NoSteamConfirmMsg,
    NoSteamConfirmPrompt,
    L2AccountItem,
    LoginPromptTitle,
    LoginPromptAccount,
    LoginPromptPassword,
    TokenExpiredTitle,
    TokenExpiredMsg,
    TokenExpiredPrompt,
    ReloginTitle,
    ReloginPrompt,
    L3QuickInputHint,
    CsvExportTitle,
    CsvExportMsg,
    CsvExportDetail,
    CsvExportSuccessTitle,
    CsvExportSuccessMsg,
    CsvExportSuccessDetail,
    BatchConfirmTitle,
    BatchConfirmMsg,
    BatchConfirmDetail,
    CliExtractNoLicenseSwitch,
    CliExtractLoginFailedSwitch,
    CliExtractLocalInjected,
    CliExtractLocalSafe,

    COUNT
};

inline constexpr size_t kMsgKeyCount = static_cast<size_t>(MsgKey::COUNT);
inline constexpr size_t kLanguageCount = 3;

inline constexpr std::array<std::array<std::string_view, kLanguageCount>, kMsgKeyCount> kTranslations = {{
    // Lua Comments
    /* LuaHeader */ {
        "-- Auto-generated by extract_tickets for AppID: ",
        "-- 由 extract_tickets 自动生成，目标 AppID: ",
        "-- Generado automáticamente por extract_tickets para AppID: "
    },
    /* LuaBaseGame */ {
        "-- Base Game",
        "-- 游戏本体",
        "-- Juego Base"
    },
    /* LuaBaseManifests */ {
        "-- Base Game Manifests",
        "-- 游戏本体清单 (Manifests)",
        "-- Manifiestos del Juego Base"
    },
    /* LuaManifestMissing */ {
        "[Manifest file not present on disk]",
        "[未检测到本地清单文件]",
        "[Archivo de manifiesto no encontrado en disco]"
    },
    /* LuaOwnedDlcs */ {
        "-- Owned DLCs",
        "-- 已拥有 DLC 内容",
        "-- DLCs Adquiridos"
    },
    /* LuaDlcDepotMissing */ {
        "[Depot key or manifest missing; commented out to avoid download failure]",
        "[未获取到该 DLC 对应 Depot 的密钥或清单，已注释以避免客户端下载失败]",
        "[Falta la clave o manifiesto del Depot; comentado para evitar errores de descarga]"
    },
    /* LuaDlcManifests */ {
        "-- DLC Manifests",
        "-- DLC 清单 (Manifests)",
        "-- Manifiestos de DLC"
    },
    /* LuaAppTicket */ {
        "-- App Ownership Ticket (AppTicket)",
        "-- 正版所有权票据 (AppTicket)",
        "-- Ticket de Propiedad de la Aplicación (AppTicket)"
    },
    /* LuaAppTicketMissing */ {
        "[No valid ownership ticket detected; OpenSteamTool will automatically fall back to AppID 7 spoofing]",
        "[未检测到有效所有权票据；OpenSteamTool 将自动启用 AppID 7 通用票据兜底]",
        "[No se detectó ticket de propiedad válido; OpenSteamTool utilizará la suplantación de AppID 7]"
    },
    /* LuaETicket */ {
        "-- Encrypted App Ticket (ETicket)",
        "-- 加密应用票据 (ETicket)",
        "-- Ticket Cifrado de Aplicación (ETicket)"
    },
    /* LuaETicketNote */ {
        "[Only required by games with third-party DRM such as Denuvo; standard games do not require this]",
        "[仅 Denuvo 等第三方强加密游戏需要，普通游戏无需此项]",
        "[Solo requerido por juegos con DRM como Denuvo; los juegos estándar no lo requieren]"
    },

    // CSV Headers
    /* CsvIndex */ { "Index", "序号", "N°" },
    /* CsvAppId */ { "AppID", "AppID", "AppID" },
    /* CsvName */ { "Name", "游戏名称", "Nombre" },
    /* CsvType */ { "Type", "类型", "Tipo" },
    /* CsvOwned */ { "Owned", "个人拥有", "Propio" },
    /* CsvShared */ { "Shared", "家庭共享", "Compartido" },

    // TUI Level 1
    /* L1HeaderTagLocal */ { "Mode: Local Mode", "模式: 本地模式", "Modo: Modo Local" },
    /* L1HeaderTagNoSteam */ { "Notice: Local Steam not detected", "提示: 未检测到本地 Steam", "Aviso: Steam local no detectado" },
    /* L1BoxTitle */ { "Local Credentials Extraction", "本地游戏凭据提取", "Extracción Local de Credenciales" },
    /* L1Welcome */ { "Welcome to extract_tickets (Steam Credentials Extractor)", "欢迎使用 extract_tickets (Steam 凭据提取工具)", "Bienvenido a extract_tickets (Extractor de Credenciales)" },
    /* L1LocalDesc */ { "Connects to local Steam client or cache to generate tickets and Lua scripts.", "直连本地 Steam 客户端或缓存，快速提取游戏凭据并生成 Lua 配置。", "Conecta con el cliente Steam o caché local para generar tickets y scripts Lua." },
    /* L1NoSteamNotice */ { "Local Steam not detected. Press [O] to switch to Online Mode without client!", "未检测到本地 Steam，按 [O] 可切换至【在线模式】免客户端提取！", "Steam local no detectado. ¡Presione [O] para cambiar al Modo En Línea!" },
    /* L1InputPrompt */ { "Target Game AppID:", "目标游戏 AppID：", "AppID del Juego:" },
    /* L1Footer */ { "[Digits] Input AppID   [Enter] Extract   [O] Online Mode   [ESC] Clear   [Q] Exit", "[数字] 输入 AppID   [Enter] 开始提取   [O] 在线模式   [ESC] 清空   [Q] 退出", "[Dígitos] AppID   [Enter] Extraer   [O] Modo En Línea   [ESC] Borrar   [Q] Salir" },

    // TUI Level 2
    /* L2HeaderTagAccounts */ { "{} saved account(s)", "已保存 {} 个账号", "{} cuenta(s) guardada(s)" },
    /* L2BoxTitle */ { "Select Steam Account for Online Extraction", "选择 Steam 账号进行在线提取", "Seleccionar Cuenta para Extracción En Línea" },
    /* L2Subtitle */ { "Credentials are securely encrypted by Windows. Only login tokens are saved, no passwords.", "所有凭据均经系统安全加密保护，仅保存登录令牌，绝不存储明文密码。", "Credenciales cifradas con Windows DPAPI. Solo se guardan tokens, nunca contraseñas." },
    /* L2ActionLogin */ { "[+] Log in New Steam Account", "[+] 登录新的 Steam 账号", "[+] Iniciar Sesión con Nueva Cuenta" },
    /* L2ActionWipe */ { "[-] Clear All Saved Credentials", "[-] 清空全部已保存凭据", "[-] Borrar Todas las Credenciales" },
    /* L2TipLogin */ { "Tip: Press Enter to log in and verify with Steam Guard; credentials will be saved.", "提示: 按 Enter 登录并完成 Steam 令牌验证，登录凭据将自动保存。", "Consejo: Presione Enter para iniciar sesión y autenticar; se guardará automáticamente." },
    /* L2TipCached */ { "Tip: Press Enter to view games list. Press [D] to delete this account.", "提示: 按 Enter 查看该账号的游戏列表；按 [D] 删除选中的账号凭据。", "Consejo: Presione Enter para ver los juegos. Presione [D] para eliminar esta cuenta." },
    /* L2TipWipe */ { "Tip: CAUTION! Press Enter to securely clear all locally stored credentials.", "提示: 危险操作！按 Enter 将彻底清除本地保存的全部账号凭据。", "Consejo: ¡PELIGRO! Presione Enter para borrar de forma segura todas las credenciales." },
    /* L2Footer */ { "[Up/Down] Navigate   [Enter] Select   [D] Delete   [ESC/Q] Return", "[↑/↓] 选择账号   [Enter] 确认进入   [D] 删除账号   [ESC/Q] 返回", "[↑/↓] Navegar   [Enter] Seleccionar   [D] Eliminar   [ESC/Q] Volver" },

    // TUI Level 3
    /* L3HeaderAccount */ { "Steam Account: {} (SteamID: {})", "Steam 账号: {} (SteamID: {})", "Cuenta de Steam: {} (SteamID: {})" },
    /* L3HeaderPage */ { "Page {} / {} (Total {} games)", "第 {} / {} 页 (共 {} 款游戏)", "Página {} / {} (Total {} juegos)" },
    /* L3BoxTitle */ { "Owned Games List (Enter AppID to extract or browse)", "已拥有游戏列表 (可直接输入 AppID 快速提取或翻页浏览)", "Lista de Juegos (Ingrese AppID para extraer o navegue)" },
    /* L3ColIndex */ { "No.", "序号", "N°" },
    /* L3ColAppId */ { "AppID", "AppID", "AppID" },
    /* L3ColName */ { "Game Title", "游戏名称", "Nombre del Juego" },
    /* L3ColStatus */ { "Status", "状态", "Estado" },
    /* L3StatusShared */ { "Shared", "共享", "Compartido" },
    /* L3StatusReady */ { "Ready", "就绪", "Listo" },
    /* L3QuickInputPrompt */ { "Quick Extract AppID:", "快速提取 AppID：", "Extracción Rápida AppID:" },
    /* L3Footer */ { "[Enter] Extract   [E] Force Eticket   [↑/↓] Select   [←/→] Page   [A] Batch All   [L] Export   [ESC/Q] Back", "[Enter] 提取   [E] 强提加密票据   [↑/↓] 选择   [←/→] 翻页   [A] 批量全部   [L] 导出清单   [ESC/Q] 返回", "[Enter] Extraer   [E] Forzar Eticket   [↑/↓] Seleccionar   [←/→] Página   [A] Extraer Todo   [L] Exportar   [ESC/Q] Volver" },

    // Modals & General
    /* BtnClose */ { "  [ Press Enter or ESC to Close ]  ", "  [ 按 Enter 或 ESC 关闭 ]  ", "  [ Presione Enter o ESC para Cerrar ]  " },
    /* BtnYes */ { "  [ Y: Confirm ]  ", "  [ Y: 确定 ]  ", "  [ Y: Confirmar ]  " },
    /* BtnNo */ { "  [ N: Cancel ]  ", "  [ N: 取消 ]  ", "  [ N: Cancelar ]  " },
    /* HintInputEnterEsc */ { "[ Enter: Submit  ESC: Cancel ]", "[ Enter: 提交  ESC: 取消 ]", "[ Enter: Enviar  ESC: Cancelar ]" },
    /* ExtractingTitle */ { "Extracting Local Credentials", "本地凭据提取中", "Extrayendo Credenciales Locales" },
    /* ExtractingLocalMsg */ { "Communicating with local Steam client to retrieve AppID {} credentials...", "正在与本地 Steam 客户端通信获取 AppID {} 凭据...", "Comunicando con cliente Steam local para AppID {}..." },
    /* ExtractingOnlineTitle */ { "Extracting Online Credentials", "在线凭据提取中", "Extrayendo Credenciales En Línea" },
    /* ExtractingOnlineMsg1 */ { "Requesting ownership tickets and decryption keys from Steam...", "正在向 Steam 请求所有权票据与解密密钥...", "Solicitando tickets de propiedad y claves a Steam..." },
    /* ExtractingOnlineMsg2 */ { "Target App: {} ({})", "目标游戏: {} ({})", "Juego Objetivo: {} ({})" },
    /* ExtractSuccessTitle */ { "Extraction Complete", "提取完成", "Extracción Completada" },
    /* ExtractSuccessMsg */ { "Credentials and Lua configuration for [{}] extracted successfully!", "游戏 [{}] 的凭据与 Lua 配置已成功提取！", "¡Credenciales y Lua para [{}] extraídos con éxito!" },
    /* ExtractSuccessDetail */ { "Files saved in ./{}/ directory", "文件已保存至 ./{}/ 目录中", "Archivos guardados en el directorio ./{}/" },
    /* ExtractWarnTitle */ { "Extraction Warning", "提取警告", "Aviso de Extracción" },
    /* ExtractWarnMsg */ { "AppID {} extracted, but some outputs may be limited", "AppID {} 提取完成，部分输出可能受限", "AppID {} extraído, pero algunas salidas pueden estar limitadas" },
    /* BatchExtractTitle */ { "Batch Extracting Credentials", "正在批量提取凭据", "Extracción de Credenciales por Lotes" },
    /* BatchAbortedTitle */ { "Batch Extraction Cancelled", "批量提取已中止", "Extracción por Lotes Cancelada" },
    /* BatchAbortedMsg */ { "Operation cancelled. Successfully processed {} / {} games.", "操作已中止，已成功处理 {} / {} 款游戏凭据。", "Operación cancelada. Se procesaron con éxito {} / {} juegos." },
    /* BatchAbortedDetail */ { "Extracted tickets and Lua scripts saved in respective AppID folders", "已生成的凭据与 Lua 脚本保存在各自 AppID 目录中", "Los archivos completados están guardados en sus directorios" },
    /* BatchSuccessTitle */ { "Batch Extraction Complete", "批量提取完成", "Extracción por Lotes Completada" },
    /* BatchSuccessMsg */ { "Successfully extracted credentials for all {} / {} games!", "已成功提取全部 {} / {} 款游戏的凭据！", "¡Extraídas con éxito las credenciales de {} / {} juegos!" },
    /* BatchSuccessDetail */ { "All configurations and Lua scripts generated in respective AppID folders", "所有凭据与 Lua 脚本均已保存在各自 AppID 目录下", "Todas las configuraciones y Lua generados en sus directorios" },
    /* DelAccountTitle */ { "Delete Account Credentials", "删除账号凭据", "Eliminar Credenciales de Cuenta" },
    /* DelAccountMsg */ { "Are you sure you want to delete credentials for account [{}]?", "确定要删除本地保存的账号 [{}] 凭据吗？", "¿Está seguro de que desea eliminar las credenciales de la cuenta [{}]?" },
    /* DelAccountDetail */ { "The saved login token will be securely removed.", "本地保存的登录令牌将被安全清除。", "El token de inicio de sesión guardado se eliminará de forma segura." },
    /* WipeAllTitle */ { "Clear All Credentials", "清空全部凭据", "Borrar Todas las Credenciales" },
    /* WipeAllMsg */ { "WARNING: Are you sure you want to clear ALL saved credentials?", "警告：确定要清除本地保存的所有账号凭据吗？", "ADVERTENCIA: ¿Está seguro de que desea borrar TODAS las credenciales guardadas?" },
    /* WipeAllDetail */ { "All saved credentials for all accounts will be permanently deleted.", "本地保存的所有账号凭据均将被彻底清除。", "Todas las credenciales guardadas serán eliminadas permanentemente." },
    /* LoginFailedTitle */ { "Login Failed", "登录失败", "Error de Inicio de Sesión" },
    /* LoginFailedDefaultMsg */ { "Incorrect account name or password", "账号或密码错误", "Nombre de cuenta o contraseña incorrectos" },
    /* LoginFailedDetail */ { "Please check network connection and 2FA code input", "请检查网络连接及动态验证码输入", "Por favor, verifique la conexión de red y el código 2FA." },
    /* InvalidAppId */ { "Invalid AppID (must be a positive integer)", "无效的 AppID (必须为正整数)", "AppID no válido (debe ser un entero positivo)" },
    /* GuardMobileTitle */ { "Steam Mobile Authenticator", "Steam 手机令牌", "Autenticador Móvil Steam Guard" },
    /* GuardMobilePrompt */ { "Account requires mobile authenticator. Enter the 5-character TOTP code:", "账号已启用手机令牌，请输入手机 App 上的 5 位动态验证码:", "La cuenta requiere autenticador móvil. Ingrese el código dinámico de 5 caracteres:" },
    /* GuardEmailTitle */ { "Steam Guard Email Code", "Steam 邮箱验证码", "Código de Correo Steam Guard" },
    /* GuardEmailPrompt */ { "Verification code sent to email ({}). Enter the code:", "验证码已发送至邮箱 ({})，请输入邮件中的验证码:", "Código de verificación enviado al correo ({}). Ingrese el código:" },
    /* GuardDeviceTitle */ { "Steam Mobile Confirmation", "Steam 手机确认", "Confirmación Móvil de Steam" },
    /* GuardDevicePrompt */ { "Please tap [Confirm Login] in your Steam Mobile App", "请在手机 Steam App 上点击【确认登录】", "Por favor presione [Confirmar inicio de sesión] en la app Steam" },
    /* GuardDeviceDetail */ { "Press Enter once confirmed, or ESC to cancel...", "手机确认通过后按 Enter 继续，按 ESC 取消...", "Presione Enter una vez confirmado, o ESC para cancelar..." },
    /* ErrNoSavedAccounts */ { "[ERROR] No authorized Steam credentials found locally.", "[ERROR] 本地未检测到已授权的 Steam 账号凭据。", "[ERROR] No se encontraron credenciales autorizadas de Steam localmente." },
    /* ErrNoSavedAccountsTip */ { "[Tip] Please run 'extract_tickets --online' to login and save credentials first.", "[提示] 请先运行 extract_tickets --online 登录并保存凭据。", "[Consejo] Ejecute 'extract_tickets --online' para iniciar sesión y guardar credenciales." },
    /* ErrAccountNotFound */ { "[ERROR] Specified saved account not found: '{}'", "[ERROR] 未找到指定的已保存账号: '{}'", "[ERROR] No se encontró la cuenta guardada especificada: '{}'" },
    /* ErrAccountListTip */ { "[Tip] Currently saved accounts:", "[提示] 当前已保存的账号列表:", "[Consejo] Cuentas guardadas actualmente:" },
    /* ErrAuthTimeoutOrCancelled */ { "Authentication timed out or user cancelled authorization", "认证超时或用户取消授权", "Tiempo de autenticación agotado o cancelado por el usuario" },
    /* ErrUserCancelledInput */ { "User cancelled 2FA code input", "用户取消二次验证输入", "Usuario canceló el ingreso del código 2FA" },
    /* ErrUserCancelledDevice */ { "User cancelled mobile confirmation", "用户取消手机确认", "Usuario canceló la confirmación móvil" },
    /* ErrUserCancelledPwd */ { "User cancelled password input", "用户取消输入密码", "Usuario canceló el ingreso de contraseña" },
    /* ErrUserCancelledPoll */ { "User cancelled authorization", "用户取消登录授权", "Usuario canceló el sondeo de autenticación" },
    /* ErrRsaKeyFailed */ { "Failed to obtain RSA public key from Steam server", "无法从 Steam 服务器获取安全 RSA 公钥", "No se pudo obtener la clave pública RSA de Steam" },
    /* ErrAuthSessionFailed */ { "Failed to begin authentication session; check account and password", "发起认证会话失败，请检查账号密码是否正确", "Fallo al iniciar sesión de autenticación; verifique usuario y contraseña" },
    /* ConnectingTitle */ { "Connecting to Steam Servers", "正在连接 Steam 服务器", "Conectando a los Servidores de Steam" },
    /* ConnectingGatewayMsg */ { "Connecting to Steam network and signing in...", "正在连接 Steam 官方网络并登录...", "Conectando a la red de Steam e iniciando sesión..." },
    /* ConnectingRefreshingMsg */ { "Login token expired, automatically refreshing session...", "登录凭据已过期，正在自动刷新会话...", "Token expirado, renovando sesión automáticamente..." },
    /* ConnectingFailedTitle */ { "Connection Failed", "连接失败", "Fallo de Conexión" },
    /* ConnectingFailedMsg */ { "Failed to connect to Steam servers", "无法连接至 Steam 服务器", "No se pudo conectar a los servidores de Steam" },
    /* ConnectingFailedDetail */ { "Please check network connection or system proxy settings", "请检查网络连接或系统代理设置", "Por favor verifique su conexión a internet o proxy" },
    /* SyncingGamesMsg */ { "Login successful! Syncing games list...", "登录成功！正在同步游戏列表...", "¡Inicio de sesión exitoso! Sincronizando biblioteca de juegos..." },
    /* NoGamesFoundTitle */ { "No Games Found", "未发现游戏", "No se Encontraron Juegos" },
    /* NoGamesFoundMsg */ { "No owned games detected on this account", "当前账号下未检测到拥有的游戏", "No se detectaron juegos adquiridos en esta cuenta" },
    /* NoGamesFoundDetail */ { "You can still quick extract by typing AppID directly", "您仍可直接输入 AppID 快速提取凭据", "Aún puede extraer ingresando el AppID directamente" },
    /* CliExtractAttempting */ { "[INFO] Trying account [{}] ({}/{})...", "[INFO] 正在尝试账号 [{}] ({}/{})...", "[INFO] Probando cuenta [{}] ({}/{})..." },
    /* CliExtractUsing */ { "[INFO] Using account [{}] for cloud extraction (Target AppID: {})...", "[INFO] 正在使用账号 [{}] 进行云端凭据提取 (目标 AppID: {})...", "[INFO] Usando cuenta [{}] para extracción en la nube (AppID Objetivo: {})..." },
    /* CliExtractTokenExpired */ { "  -> Access token expired, automatically renewing via official API...", "  -> 当前访问凭据已过期，尝试通过官方接口自动续期...", "  -> Token expirado, renovando automáticamente vía API oficial..." },
    /* CliExtractLoginSuccess */ { "  -> Steam login succeeded, extracting tickets, keys and manifests...", "  -> Steam 登录成功，正在提取票据、密钥与清单...", "  -> Inicio de sesión en Steam exitoso, extrayendo tickets, claves y manifiestos..." },
    /* CliExtractFallbackBase */ { "No saved accounts own AppID {}; generating base configuration from metadata", "所有已保存账号均未拥有 AppID {}，使用基础元数据生成通用配置", "Ninguna cuenta guardada posee AppID {}; generando configuración base desde metadatos" },
    /* CliExtractSuccess */ { "[OK] AppID {} credentials extracted successfully! Outputs written to ./{}/ directory.", "[OK] AppID {} 凭据提取成功！输出文件已写入 ./{}/ 目录。", "¡[OK] Credenciales para AppID {} extraídas con éxito! Archivos guardados en ./{}/." },
    /* CliExtractWarn */ { "[WARN] AppID {} extraction completed, but some outputs may be limited.", "[WARN] AppID {} 凭据提取完成，但部分输出受限。", "[AVISO] Extracción de AppID {} completada, pero algunas salidas están limitadas." },
    /* CliExtractFailedAll */ { "[ERROR] Login verification failed for all saved accounts.", "[ERROR] 本地已保存账号的登录凭据均验证失败。", "[ERROR] Falló la verificación de inicio de sesión para todas las cuentas guardadas." },
    /* CliExtractFailedAllTip */ { "[Tip] Run 'extract_tickets --online' to log in again and update credentials.", "[提示] 请运行 extract_tickets --online 重新登录以更新凭据。", "[Consejo] Ejecute 'extract_tickets --online' para volver a iniciar sesión y actualizar credenciales." },
    /* TimestampUnknown */ { "Unknown", "未知时间", "Desconocido" },
    /* L1NavTitle */ { "[Quick Navigation]", "[快捷导航]", "[Navegación Rápida]" },
    /* L1NavOnline */ { "• Press [O] -- Switch to Online Mode (Extract directly from cloud)", "• 按 [O] 键 ── 进入「在线模式」(免客户端云端提取)", "• Presione [O] -- Cambiar a \"Modo En Línea\" (Extracción en la nube sin cliente)" },
    /* L1NavExit */ { "• Press [Q] -- Exit application", "• 按 [Q] 键 ── 退出程序", "• Presione [Q] -- Salir del programa" },
    /* L1InputTip */ { "(Enter digits, press Enter to extract)", "(输入纯数字，按 Enter 开始提取)", "(Solo dígitos, presione Enter para extraer)" },
    /* NoSteamConfirmTitle */ { "Local Steam Client Not Found", "未检测到本地 Steam 客户端", "Cliente Steam Local No Detectado" },
    /* NoSteamConfirmMsg */ { "Steam is not running or installed locally; cannot extract local credentials.", "本地未检测到运行中的 Steam 客户端，无法在本地模式下提取凭据。", "Steam no está instalado o en ejecución localmente; no se pueden extraer credenciales." },
    /* NoSteamConfirmPrompt */ { "Switch to Online Mode to extract directly via Steam cloud?", "是否切换至【在线模式】免客户端直接提取？", "¿Desea cambiar al Modo En Línea para extraer directamente desde la nube?" },
    /* L2AccountItem */ { "   [{}] {}  (Last login: {}) [Authorized]", "   [{}] {}  (上次登录: {}) [凭据有效]", "   [{}] {}  (Último acceso: {}) [Autorizado]" },
    /* LoginPromptTitle */ { "Steam Account Login", "Steam 账号登录", "Iniciar Sesión de Steam" },
    /* LoginPromptAccount */ { "Enter Steam account name:", "请输入 Steam 登录账号:", "Ingrese el nombre de la cuenta de Steam:" },
    /* LoginPromptPassword */ { "Enter Steam password (masked):", "请输入 Steam 密码 (输入已掩盖):", "Ingrese la contraseña de Steam (enmascarada):" },
    /* TokenExpiredTitle */ { "Login Token Expired", "登录凭据已过期", "Token de Inicio de Sesión Expirado" },
    /* TokenExpiredMsg */ { "Saved credentials for [{}] have expired or are no longer valid.", "账号 [{}] 的本地登录凭据已过期或失效。", "Las credenciales guardadas para [{}] han expirado o ya no son válidas." },
    /* TokenExpiredPrompt */ { "Re-enter password to log in again now?", "是否立即重新输入密码登录该账号？", "¿Desea reingresar la contraseña para iniciar sesión ahora?" },
    /* ReloginTitle */ { "Re-login", "重新登录", "Reingresar" },
    /* ReloginPrompt */ { "Enter password for [{}]:", "请输入账号 [{}] 的密码:", "Ingrese la contraseña de [{}]:" },
    /* L3QuickInputHint */ { "(Type AppID and press Enter, or press Enter to extract selected)", "(可直接输入 AppID 回车，或按 Enter 提取当前选中游戏)", "(Ingrese AppID y presione Enter, o Enter para extraer seleccionado)" },
    /* CsvExportTitle */ { "Export Games List Table", "导出游戏列表表格", "Exportar Lista de Juegos" },
    /* CsvExportMsg */ { "Export all {} games in this account to a CSV file?", "确定要将该账号下全部 {} 款游戏导出为 CSV 表格吗？", "¿Desea exportar los {} juegos de esta cuenta a un archivo CSV?" },
    /* CsvExportDetail */ { "Output file: gameslist-{}.csv", "输出文件: gameslist-{}.csv", "Archivo de salida: gameslist-{}.csv" },
    /* CsvExportSuccessTitle */ { "Export Successful", "导出成功", "Exportación Exitosa" },
    /* CsvExportSuccessMsg */ { "Table saved to: {}", "表格已保存至: {}", "Tabla guardada en: {}" },
    /* CsvExportSuccessDetail */ { "Encoded in UTF-8 with BOM; opens directly in Excel and spreadsheet apps.", "采用 UTF-8 BOM 编码，支持 Excel 或 WPS 直接双击打开查看。", "Codificado en UTF-8 con BOM; se puede abrir directamente en Excel u otros visores." },
    /* BatchConfirmTitle */ { "Batch Extract Credentials", "批量提取凭据", "Extracción de Credenciales por Lotes" },
    /* BatchConfirmMsg */ { "Batch extract credentials for all {} games in this account?", "确定要批量提取当前账号下全部 {} 款游戏的凭据吗？", "¿Desea extraer por lotes las credenciales de los {} juegos de esta cuenta?" },
    /* BatchConfirmDetail */ { "Automatically extracts tickets, keys and Lua scripts (safely rate-limited).", "程序将按序自动提取票据、密钥与 Lua 脚本 (内置限速保护账号安全)", "Se extraerán automáticamente tickets, claves y scripts Lua (con límite seguro)." },
    /* CliExtractNoLicenseSwitch */ { "[INFO] Account [{}] has no license for AppID {} (no tickets/keys); trying next account...", "[INFO] 账号 [{}] 未拥有 AppID {} 的正版许可 (无票据或解密密钥)，自动尝试下一账号...", "[INFO] La cuenta [{}] no posee licencia para AppID {} (sin tickets/claves); probando siguiente cuenta..." },
    /* CliExtractLoginFailedSwitch */ { "[WARN] Account [{}] login failed; automatically trying next available account...", "[WARN] 账号 [{}] 登录失败，自动尝试下一个可用账号...", "[AVISO] Falló el inicio de sesión para [{}]; probando siguiente cuenta disponible..." },
    /* CliExtractLocalInjected */ { "[INFO] Environment set for AppID {}; preparing full extraction including eticket.bin.", "[INFO] 已为游戏 AppID {} 准备运行环境，将提取包括 eticket.bin 在内的完整凭据。", "[INFO] Entorno configurado para AppID {}; preparando extracción completa incluyendo eticket.bin." },
    /* CliExtractLocalSafe */ { "[INFO] Target AppID {} not installed locally; safe offline extraction mode enabled.", "[INFO] 目标 AppID {} 未在本地安装，已启用离线安全提取模式。", "[INFO] El AppID {} no está instalado localmente; modo seguro habilitado." }
}};

class I18n {
public:
    static Language DetectSystemLanguage() noexcept {
        char envBuf[64]{0};
#if defined(_WIN32)
        DWORD envLen = GetEnvironmentVariableA("OST_LANG", envBuf, sizeof(envBuf));
        if (envLen > 0 && envLen < sizeof(envBuf)) {
            std::string_view envVal(envBuf);
            if (envVal.starts_with("zh") || envVal.starts_with("ZH") || envVal == "chinese" || envVal == "schinese") {
                return Language::Chinese;
            }
            if (envVal.starts_with("es") || envVal.starts_with("ES") || envVal == "spanish") {
                return Language::Spanish;
            }
            if (envVal.starts_with("en") || envVal.starts_with("EN") || envVal == "english") {
                return Language::English;
            }
        }

        LANGID langId = GetUserDefaultUILanguage();
        WORD primaryLang = PRIMARYLANGID(langId);
        if (primaryLang == LANG_CHINESE) {
            return Language::Chinese;
        }
        if (primaryLang == LANG_SPANISH) {
            return Language::Spanish;
        }
#endif
        return Language::English;
    }

    static Language GetCurrentLanguage() noexcept {
        return s_currentLang;
    }

    static void SetLanguage(Language lang) noexcept {
        s_currentLang = lang;
#if defined(_WIN32)
        SetEnvironmentVariableA("OST_LANG", GetLanguageCode(lang).data());
#endif
    }

    static void InitLanguage() noexcept {
        SetLanguage(DetectSystemLanguage());
    }

    [[nodiscard]] static std::string_view GetLanguageCode(Language lang = s_currentLang) noexcept {
        switch (lang) {
            case Language::Chinese: return "zh";
            case Language::Spanish: return "es";
            case Language::English:
            default:                return "en";
        }
    }

    [[nodiscard]] static const char* GetSteamLanguageCode(Language lang = s_currentLang) noexcept {
        switch (lang) {
            case Language::Chinese: return "schinese";
            case Language::Spanish: return "spanish";
            case Language::English:
            default:                return "english";
        }
    }

    [[nodiscard]] static std::string_view Get(MsgKey key) noexcept {
        const size_t kIdx = static_cast<size_t>(key);
        if (kIdx >= kMsgKeyCount) return "";
        const size_t lIdx = static_cast<size_t>(s_currentLang);
        return kTranslations[kIdx][lIdx < kLanguageCount ? lIdx : 0];
    }

private:
    static inline Language s_currentLang{Language::English};
};

[[nodiscard]] inline std::string_view TR(MsgKey key) noexcept {
    return I18n::Get(key);
}

template <typename... Args>
[[nodiscard]] inline std::string TR_FMT(MsgKey key, Args&&... args) {
    return std::vformat(TR(key), std::make_format_args(args...));
}

} // namespace OST::ExtractTickets
