#pragma once

#include <format>
#include <string>
#include <string_view>

namespace OST::ExtractTickets {

enum class Language : size_t {
    English = 0,
    Chinese = 1,
    Spanish = 2,
    COUNT
};

inline constexpr size_t kLanguageCount = static_cast<size_t>(Language::COUNT);

#define OST_I18N_MESSAGES(M) \
    M(LuaHeader, "-- Auto-generated by extract_tickets for AppID: ", "-- 由 extract_tickets 自动生成，目标 AppID: ", "-- Generado automáticamente por extract_tickets para AppID: ") \
    M(LuaBaseGame, "-- Base Game", "-- 游戏本体", "-- Juego Base") \
    M(LuaBaseManifests, "-- Base Game Manifests", "-- 游戏本体清单 (Manifests)", "-- Manifiestos del Juego Base") \
    M(LuaManifestMissing, "[Manifest file not present on disk]", "[未检测到本地清单文件]", "[Archivo de manifiesto no encontrado en disco]") \
    M(LuaOwnedDlcs, "-- Owned DLCs", "-- 已拥有 DLC 内容", "-- DLCs Adquiridos") \
    M(LuaDlcDepotMissing, "[Depot key or manifest missing; commented out to avoid download failure]", "[未获取到该 DLC 对应 Depot 的密钥或清单，已注释以避免客户端下载失败]", "[Falta la clave o manifiesto del Depot; comentado para evitar errores de descarga]") \
    M(LuaDlcManifests, "-- DLC Manifests", "-- DLC 清单 (Manifests)", "-- Manifiestos de DLC") \
    M(LuaAppTicket, "-- App Ownership Ticket (AppTicket)", "-- 正版所有权票据 (AppTicket)", "-- Ticket de Propiedad de la Aplicación (AppTicket)") \
    M(LuaAppTicketMissing, "[No valid ownership ticket detected; OpenSteamTool will automatically fall back to AppID 7 spoofing]", "[未检测到有效所有权票据；OpenSteamTool 将自动启用 AppID 7 通用票据兜底]", "[No se detectó ticket de propiedad válido; OpenSteamTool utilizará la suplantación de AppID 7]") \
    M(LuaETicket, "-- Encrypted App Ticket (ETicket)", "-- 加密应用票据 (ETicket)", "-- Ticket Cifrado de Aplicación (ETicket)") \
    M(LuaETicketNote, "[Only required by games with third-party DRM such as Denuvo; standard games do not require this]", "[仅 Denuvo 等第三方强加密游戏需要，普通游戏无需此项]", "[Solo requerido por juegos con DRM como Denuvo; los juegos estándar no lo requieren]") \
    M(CsvIndex, "Index", "序号", "N°") \
    M(CsvAppId, "AppID", "AppID", "AppID") \
    M(CsvName, "Name", "游戏名称", "Nombre") \
    M(CsvType, "License", "授权", "Licencia") \
    M(CsvOwned, "Owned", "个人拥有", "Propio") \
    M(CsvShared, "Shared", "家庭共享", "Compartido") \
    M(L1HeaderTagLocal, "Mode: Local Mode", "模式: 本地模式", "Modo: Modo Local") \
    M(L1HeaderTagNoSteam, "Notice: Local Steam not detected", "提示: 未检测到本地 Steam", "Aviso: Steam local no detectado") \
    M(L1BoxTitle, "Local Credentials Extraction", "本地游戏凭据提取", "Extracción Local de Credenciales") \
    M(L1Welcome, "Welcome to extract_tickets (Steam Credentials Extractor)", "欢迎使用 extract_tickets (Steam 凭据提取工具)", "Bienvenido a extract_tickets (Extractor de Credenciales)") \
    M(L1LocalDesc, "Connects to local Steam client or cache to generate tickets and Lua scripts.", "直连本地 Steam 客户端或缓存，快速提取游戏凭据并生成 Lua 配置。", "Conecta con el cliente Steam o caché local para generar tickets y scripts Lua.") \
    M(L1NoSteamNotice, "Local Steam not detected. Press [O] to switch to Online Mode without client!", "未检测到本地 Steam，按 [O] 可切换至【在线模式】免客户端提取！", "Steam local no detectado. ¡Presione [O] para cambiar al Modo En Línea!") \
    M(L1InputPrompt, "Target Game AppID:", "目标游戏 AppID：", "AppID del Juego:") \
    M(L1Footer, "[Digits] AppID   [Enter] Extract   [E] Force   [O] Online Mode   [ESC] Clear   [Q] Exit", "[数字] 输入 AppID   [Enter] 提取   [E] 强提加密   [O] 在线模式   [ESC] 清空   [Q] 退出", "[Dígitos] AppID   [Enter] Extraer   [E] Forzar   [O] Modo En Línea   [ESC] Borrar   [Q] Salir") \
    M(L2HeaderTagAccounts, "{} saved account(s)", "已保存 {} 个账号", "{} cuenta(s) guardada(s)") \
    M(L2BoxTitle, "Select Steam Account for Online Extraction", "选择 Steam 账号进行在线提取", "Seleccionar Cuenta para Extracción En Línea") \
    M(L2Subtitle, "Credentials are securely encrypted by Windows. Only login tokens are saved, no passwords.", "所有凭据均经系统安全加密保护，仅保存登录令牌，绝不存储明文密码。", "Credenciales cifradas con Windows DPAPI. Solo se guardan tokens, nunca contraseñas.") \
    M(L2ActionLogin, "[+] Log in New Steam Account", "[+] 登录新的 Steam 账号", "[+] Iniciar Sesión con Nueva Cuenta") \
    M(L2ActionWipe, "[-] Clear All Saved Credentials", "[-] 清空全部已保存凭据", "[-] Borrar Todas las Credenciales") \
    M(L2TipLogin, "Tip: Press Enter to log in and verify with Steam Guard; credentials will be saved.", "提示: 按 Enter 登录并完成 Steam 令牌验证，登录凭据将自动保存。", "Consejo: Presione Enter para iniciar sesión y autenticar; se guardará automáticamente.") \
    M(L2TipCached, "Tip: Press Enter to view games list; press [R] to edit remark, [D] to delete.", "提示: 按 Enter 查看该账号游戏列表；按 [R] 修改备注，按 [D] 删除账号。", "Consejo: Presione Enter para ver los juegos; presione [R] para editar nota, [D] para eliminar.") \
    M(L2TipCachedNoAlias, "Tip: Press Enter to view games list; press [R] to set remark, [D] to delete.", "提示: 按 Enter 查看该账号游戏列表；按 [R] 设置备注，按 [D] 删除账号。", "Consejo: Presione Enter para ver los juegos; presione [R] para nota, [D] para eliminar.") \
    M(L2TipWipe, "Warning: Press Enter to permanently delete all saved credentials on this computer.", "警告: 按 Enter 将彻底清除本地保存的所有账号凭据。", "Advertencia: Presione Enter para eliminar permanentemente todas las credenciales guardadas.") \
    M(L2Footer, "[Up/Down] Navigate   [Enter] Select   [R] Remark   [D] Delete   [ESC/Q] Return", "[↑/↓] 选择账号   [Enter] 确认进入   [R] 备注   [D] 删除账号   [ESC/Q] 返回", "[↑/↓] Navegar   [Enter] Seleccionar   [R] Nota   [D] Eliminar   [ESC/Q] Volver") \
    M(L2FooterInvalid, "[Up/Down] Navigate   [Enter] Re-login   [R] Remark   [D] Delete   [ESC/Q] Return", "[↑/↓] 选择账号   [Enter] 重新登录   [R] 备注   [D] 删除账号   [ESC/Q] 返回", "[↑/↓] Navegar   [Enter] Reingresar   [R] Nota   [D] Eliminar   [ESC/Q] Volver") \
    M(L2TipInvalidAccount, "Hint: Credentials have expired; press Enter to re-login, [R] to edit remark, [D] to delete.", "提示: 该账号登录凭据已失效，按 Enter 重新登录，按 [R] 修改备注，按 [D] 删除账号。", "Aviso: Credenciales expiradas; Enter para reingresar, [R] para editar nota, [D] para eliminar.") \
    M(L2TipInvalidAccountNoAlias, "Hint: Credentials have expired; press Enter to re-login, [R] to set remark, [D] to delete.", "提示: 该账号登录凭据已失效，按 Enter 重新登录，按 [R] 设置备注，按 [D] 删除账号。", "Aviso: Credenciales expiradas; Enter para reingresar, [R] para agregar nota, [D] para eliminar.") \
    M(L2TagValidCredential, "[Authorized]", "[凭据有效]", "[Autorizado]") \
    M(L2TagInvalidCredential, "[Expired]", "[凭据失效]", "[Expirado]") \
    M(EditAliasTitle, "Edit Account Remark", "修改账号备注", "Editar Nota de Cuenta") \
    M(EditAliasPrompt, "Enter remark for [{}]: (leave blank and press Enter to clear)", "请输入账号 [{}] 的备注标签 (留空并按 Enter 可清除备注):", "Ingrese nota para [{}]: (en blanco para borrar)") \
    M(SetAliasTitle, "Set Account Remark", "设置账号备注", "Agregar Nota de Cuenta") \
    M(SetAliasPrompt, "Enter remark for [{}]:", "请输入账号 [{}] 的备注标签:", "Ingrese nota para [{}]:") \
    M(L3HeaderAccount, "Steam Account: {} (SteamID: {})", "Steam 账号: {} (SteamID: {})", "Cuenta de Steam: {} (SteamID: {})") \
    M(L3HeaderPage, "Page {} / {} (Total {} games)", "第 {} / {} 页 (共 {} 款游戏)", "Página {} / {} (Total {} juegos)") \
    M(L3BoxTitle, "Owned Games List (Enter AppID to extract or browse)", "已拥有游戏列表 (可直接输入 AppID 快速提取或翻页浏览)", "Lista de Juegos (Ingrese AppID para extraer o navegue)") \
    M(L3ColIndex, "No.", "序号", "N°") \
    M(L3ColAppId, "AppID", "AppID", "AppID") \
    M(L3ColName, "Game Title", "游戏名称", "Nombre del Juego") \
    M(L3ColLicense, "License", "授权", "Licencia") \
    M(L3StatusShared, "Shared", "共享", "Compartido") \
    M(L3StatusOwned, "Owned", "自有", "Propio") \
    M(L3QuickInputPrompt, "Quick Extract AppID:", "快速提取 AppID：", "Extracción Rápida AppID:") \
    M(L3Footer, "[Enter] Extract  [E] Force  [↑/↓] Select  [←/→] Page  [A] Batch  [L] CSV  [ESC/Q] Back", "[Enter] 提取  [E] 强提加密  [↑/↓] 选择  [←/→] 翻页  [A] 批量  [L] 导出  [ESC/Q] 返回", "[Enter] Extraer  [E] Forzar  [↑/↓] Mover  [←/→] Pág  [A] Todo  [L] CSV  [ESC/Q] Volver") \
    M(BtnClose, "  [ Press Enter or ESC to Close ]  ", "  [ 按 Enter 或 ESC 关闭 ]  ", "  [ Presione Enter o ESC para Cerrar ]  ") \
    M(BtnYes, "  [ Y: Confirm ]  ", "  [ Y: 确定 ]  ", "  [ Y: Confirmar ]  ") \
    M(BtnNo, "  [ N: Cancel ]  ", "  [ N: 取消 ]  ", "  [ N: Cancelar ]  ") \
    M(HintInputEnterEsc, "[ Enter: Submit  ESC: Cancel ]", "[ Enter: 提交  ESC: 取消 ]", "[ Enter: Enviar  ESC: Cancelar ]") \
    M(ExtractingTitle, "Extracting Local Credentials", "本地凭据提取中", "Extrayendo Credenciales Locales") \
    M(ExtractingLocalMsg, "Communicating with local Steam client to retrieve AppID {} credentials...", "正在与本地 Steam 客户端通信获取 AppID {} 凭据...", "Comunicando con cliente Steam local para AppID {}...") \
    M(ExtractingOnlineTitle, "Extracting Online Credentials", "在线凭据提取中", "Extrayendo Credenciales En Línea") \
    M(ExtractingOnlineMsg1, "Requesting ownership tickets and decryption keys from Steam...", "正在向 Steam 请求所有权票据与解密密钥...", "Solicitando tickets de propiedad y claves a Steam...") \
    M(ExtractingOnlineMsg2, "Target App: {} ({})", "目标游戏: {} ({})", "Juego Objetivo: {} ({})") \
    M(ExtractingManifestProgress, "Downloading manifests: [{}/{}] (Depot {})", "正在下载官方清单: [{}/{}] (Depot {})", "Descargando manifiestos: [{}/{}] (Depot {})") \
    M(ExtractingManifestsDone, "All official manifests downloaded successfully", "官方清单文件已全部下载就绪", "Todos los manifiestos descargados con éxito") \
    M(ExtractSuccessTitle, "Extraction Complete", "提取完成", "Extracción Completada") \
    M(ExtractSuccessMsg, "Credentials and Lua configuration for [{}] extracted successfully!", "游戏 [{}] 的凭据与 Lua 配置已成功提取！", "¡Credenciales y Lua para [{}] extraídos con éxito!") \
    M(ExtractSuccessDetail, "Files saved in ./{}/ directory", "文件已保存至 ./{}/ 目录中", "Archivos guardados en el directorio ./{}/") \
    M(ExtractWarnTitle, "Extraction Warning", "提取警告", "Aviso de Extracción") \
    M(ExtractWarnMsg, "AppID {} extracted, but some outputs may be limited", "AppID {} 提取完成，部分输出可能受限", "AppID {} extraído, pero algunas salidas pueden estar limitadas") \
    M(BatchExtractTitle, "Batch Extracting Credentials", "正在批量提取凭据", "Extracción de Credenciales por Lotes") \
    M(BatchAbortedTitle, "Batch Extraction Cancelled", "批量提取已中止", "Extracción por Lotes Cancelada") \
    M(BatchAbortedMsg, "Operation cancelled. Successfully processed {} / {} games.", "操作已中止，已成功处理 {} / {} 款游戏凭据。", "Operación cancelada. Se procesaron con éxito {} / {} juegos.") \
    M(BatchAbortedDetail, "Extracted tickets and Lua scripts saved in respective AppID folders", "已生成的凭据与 Lua 脚本保存在各自 AppID 目录中", "Los archivos completados están guardados en sus directorios") \
    M(BatchSuccessTitle, "Batch Extraction Complete", "批量提取完成", "Extracción por Lotes Completada") \
    M(BatchSuccessMsg, "Successfully extracted credentials for all {} / {} games!", "已成功提取全部 {} / {} 款游戏的凭据！", "¡Extraídas con éxito las credenciales de {} / {} juegos!") \
    M(BatchSuccessDetail, "All configurations and Lua scripts generated in respective AppID folders", "所有凭据与 Lua 脚本均已保存在各自 AppID 目录下", "Todas las configuraciones y Lua generados en sus directorios") \
    M(DelAccountTitle, "Delete Account Credentials", "删除账号凭据", "Eliminar Credenciales de Cuenta") \
    M(DelAccountMsg, "Are you sure you want to delete credentials for account [{}]?", "确定要删除本地保存的账号 [{}] 凭据吗？", "¿Está seguro de que desea eliminar las credenciales de la cuenta [{}]?") \
    M(DelAccountDetail, "The saved login token will be securely removed.", "本地保存的登录令牌将被安全清除。", "El token de inicio de sesión guardado se eliminará de forma segura.") \
    M(WipeAllTitle, "Clear All Credentials", "清空全部凭据", "Borrar Todas las Credenciales") \
    M(WipeAllMsg, "WARNING: Are you sure you want to clear ALL saved credentials?", "警告：确定要清除本地保存的所有账号凭据吗？", "ADVERTENCIA: ¿Está seguro de que desea borrar TODAS las credenciales guardadas?") \
    M(WipeAllDetail, "All saved credentials for all accounts will be permanently deleted.", "本地保存的所有账号凭据均将被彻底清除。", "Todas las credenciales guardadas serán eliminadas permanentemente.") \
    M(LoginFailedTitle, "Login Failed", "登录失败", "Error de Inicio de Sesión") \
    M(LoginFailedDefaultMsg, "Incorrect account name or password", "账号或密码错误", "Nombre de cuenta o contraseña incorrectos") \
    M(LoginFailedDetail, "Please check network connection and 2FA code input", "请检查网络连接及动态验证码输入", "Por favor, verifique la conexión de red y el código 2FA.") \
    M(InvalidAppId, "Invalid AppID (must be a positive integer)", "无效的 AppID (必须为正整数)", "AppID no válido (debe ser un entero positivo)") \
    M(GuardMobileTitle, "Steam Mobile Authenticator", "Steam 手机令牌", "Autenticador Móvil Steam Guard") \
    M(GuardMobilePrompt, "Account requires mobile authenticator. Enter the 5-character TOTP code:", "账号已启用手机令牌，请输入手机 App 上的 5 位动态验证码:", "La cuenta requiere autenticador móvil. Ingrese el código dinámico de 5 caracteres:") \
    M(GuardEmailTitle, "Steam Guard Email Code", "Steam 邮箱验证码", "Código de Correo Steam Guard") \
    M(GuardEmailPrompt, "Verification code sent to email ({}). Enter the code:", "验证码已发送至邮箱 ({})，请输入邮件中的验证码:", "Código de verificación enviado al correo ({}). Ingrese el código:") \
    M(GuardDeviceTitle, "Steam Mobile Confirmation", "Steam 手机确认", "Confirmación Móvil de Steam") \
    M(GuardDevicePrompt, "Please tap [Confirm Login] in your Steam Mobile App", "请在手机 Steam App 上点击【确认登录】", "Por favor presione [Confirmar inicio de sesión] en la app Steam") \
    M(GuardDeviceDetail, "Press Enter once confirmed, or ESC to cancel...", "手机确认通过后按 Enter 继续，按 ESC 取消...", "Presione Enter una vez confirmado, o ESC para cancelar...") \
    M(GuardMobileDualPrompt, "Enter 5-character TOTP code (or tap Confirm on phone and press Enter):", "请输入 5 位动态码 (或在手机 App 点击确认后直接按回车):", "Ingrese el código TOTP de 5 dígitos (o confirme en el móvil y presione Enter):") \
    M(GuardCodeIncorrect, "Authentication code incorrect or expired. Please try again:", "动态验证码错误或已失效，请重新输入:", "Código de autenticación incorrecto o expirado. Intente de nuevo:") \
    M(ErrNoSavedAccounts, "[ERROR] No authorized Steam credentials found locally.", "[ERROR] 本地未检测到已授权的 Steam 账号凭据。", "[ERROR] No se encontraron credenciales autorizadas de Steam localmente.") \
    M(ErrNoSavedAccountsTip, "[Tip] Please run 'extract_tickets --online' to login and save credentials first.", "[提示] 请先运行 extract_tickets --online 登录并保存凭据。", "[Consejo] Ejecute 'extract_tickets --online' para iniciar sesión y guardar credenciales.") \
    M(ErrAccountNotFound, "[ERROR] Specified saved account not found: '{}'", "[ERROR] 未找到指定的已保存账号: '{}'", "[ERROR] No se encontró la cuenta guardada especificada: '{}'") \
    M(ErrAccountListTip, "[Tip] Currently saved accounts:", "[提示] 当前已保存的账号列表:", "[Consejo] Cuentas guardadas actualmente:") \
    M(ErrAuthTimeoutOrCancelled, "Authentication timed out or user cancelled authorization", "认证超时或用户取消授权", "Tiempo de autenticación agotado o cancelado por el usuario") \
    M(ErrUserCancelledInput, "User cancelled 2FA code input", "用户取消二次验证输入", "Usuario canceló el ingreso del código 2FA") \
    M(ErrUserCancelledDevice, "User cancelled mobile confirmation", "用户取消手机确认", "Usuario canceló la confirmación móvil") \
    M(ErrUserCancelledPwd, "User cancelled password input", "用户取消输入密码", "Usuario canceló el ingreso de contraseña") \
    M(ErrUserCancelledPoll, "User cancelled authorization", "用户取消登录授权", "Usuario canceló el sondeo de autenticación") \
    M(ErrRsaKeyFailed, "Failed to obtain RSA public key from Steam server", "无法从 Steam 服务器获取安全 RSA 公钥", "No se pudo obtener la clave pública RSA de Steam") \
    M(ErrAuthSessionFailed, "Failed to begin authentication session; check account and password", "发起认证会话失败，请检查账号密码是否正确", "Fallo al iniciar sesión de autenticación; verifique usuario y contraseña") \
    M(ConnectingTitle, "Connecting to Steam Servers", "正在连接 Steam 服务器", "Conectando a los Servidores de Steam") \
    M(ConnectingGatewayMsg, "Connecting to Steam network and signing in...", "正在连接 Steam 官方网络并登录...", "Conectando a la red de Steam e iniciando sesión...") \
    M(ConnectingRefreshingMsg, "Login token expired, automatically refreshing session...", "登录凭据已过期，正在自动刷新会话...", "Token expirado, renovando sesión automáticamente...") \
    M(ConnectingFailedTitle, "Connection Failed", "连接失败", "Fallo de Conexión") \
    M(ConnectingFailedMsg, "Failed to connect to Steam servers", "无法连接至 Steam 服务器", "No se pudo conectar a los servidores de Steam") \
    M(ConnectingFailedDetail, "Please check network connection or system proxy settings", "请检查网络连接或系统代理设置", "Por favor verifique su conexión a internet o proxy") \
    M(SyncingGamesMsg, "Login successful! Syncing games list...", "登录成功！正在同步游戏列表...", "¡Inicio de sesión exitoso! Sincronizando biblioteca de juegos...") \
    M(NoGamesFoundTitle, "No Games Found", "未发现游戏", "No se Encontraron Juegos") \
    M(NoGamesFoundMsg, "No owned games detected on this account", "当前账号下未检测到拥有的游戏", "No se detectaron juegos adquiridos en esta cuenta") \
    M(NoGamesFoundDetail, "You can still quick extract by typing AppID directly", "您仍可直接输入 AppID 快速提取凭据", "Aún puede extraer ingresando el AppID directamente") \
    M(CliExtractAttempting, "[INFO] Trying account [{}] ({}/{})...", "[INFO] 正在尝试账号 [{}] ({}/{})...", "[INFO] Probando cuenta [{}] ({}/{})...") \
    M(CliExtractUsing, "[INFO] Using account [{}] for cloud extraction (Target AppID: {})...", "[INFO] 正在使用账号 [{}] 进行云端凭据提取 (目标 AppID: {})...", "[INFO] Usando cuenta [{}] para extracción en la nube (AppID Objetivo: {})...") \
    M(CliExtractTokenExpired, "  -> Access token expired, automatically renewing via official API...", "  -> 当前访问凭据已过期，尝试通过官方接口自动续期...", "  -> Token expirado, renovando automáticamente vía API oficial...") \
    M(CliExtractLoginSuccess, "  -> Steam login succeeded, extracting tickets, keys and manifests...", "  -> Steam 登录成功，正在提取票据、密钥与清单...", "  -> Inicio de sesión en Steam exitoso, extrayendo tickets, claves y manifiestos...") \
    M(CliExtractFallbackBase, "No saved accounts own AppID {}; generating base configuration from metadata", "所有已保存账号均未拥有 AppID {}，使用基础元数据生成通用配置", "Ninguna cuenta guardada posee AppID {}; generando configuración base desde metadatos") \
    M(CliExtractSuccess, "[OK] AppID {} credentials extracted successfully! Outputs written to ./{}/ directory.", "[OK] AppID {} 凭据提取成功！输出文件已写入 ./{}/ 目录。", "¡[OK] Credenciales para AppID {} extraídas con éxito! Archivos guardados en ./{}/.") \
    M(CliExtractWarn, "[WARN] AppID {} extraction completed, but some outputs may be limited.", "[WARN] AppID {} 凭据提取完成，但部分输出受限。", "[AVISO] Extracción de AppID {} completada, pero algunas salidas están limitadas.") \
    M(CliExtractFailedAll, "[ERROR] Login verification failed for all saved accounts.", "[ERROR] 本地已保存账号的登录凭据均验证失败。", "[ERROR] Falló la verificación de inicio de sesión para todas las cuentas guardadas.") \
    M(CliExtractFailedAllTip, "[Tip] Run 'extract_tickets --online' to log in again and update credentials.", "[提示] 请运行 extract_tickets --online 重新登录以更新凭据。", "[Consejo] Ejecute 'extract_tickets --online' para volver a iniciar sesión y actualizar credenciales.") \
    M(TimestampUnknown, "Unknown", "未知时间", "Desconocido") \
    M(L1NavTitle, "[Quick Navigation]", "[快捷导航]", "[Navegación Rápida]") \
    M(L1NavOnline, "• Press [O] -- Switch to Online Mode (Extract directly from cloud)", "• 按 [O] 键 ── 进入「在线模式」(免客户端云端提取)", "• Presione [O] -- Cambiar a \"Modo En Línea\" (Extracción en la nube sin cliente)") \
    M(L1NavExit, "• Press [Q] -- Exit application", "• 按 [Q] 键 ── 退出程序", "• Presione [Q] -- Salir del programa") \
    M(L1InputTip, "(Enter digits, press Enter to extract)", "(输入纯数字，按 Enter 开始提取)", "(Solo dígitos, presione Enter para extraer)") \
    M(NoSteamConfirmTitle, "Local Steam Client Not Found", "未检测到本地 Steam 客户端", "Cliente Steam Local No Detectado") \
    M(NoSteamConfirmMsg, "Steam is not running or installed locally; cannot extract local credentials.", "本地未检测到运行中的 Steam 客户端，无法在本地模式下提取凭据。", "Steam no está instalado o en ejecución localmente; no se pueden extraer credenciales.") \
    M(NoSteamConfirmPrompt, "Switch to Online Mode to extract directly via Steam cloud?", "是否切换至【在线模式】免客户端直接提取？", "¿Desea cambiar al Modo En Línea para extraer directamente desde la nube?") \
    M(L2AccountItem, "   [{}] {}  (Last login: {})", "   [{}] {}  (上次登录: {})", "   [{}] {}  (Último acceso: {})") \
    M(LoginPromptTitle, "Steam Account Login", "Steam 账号登录", "Iniciar Sesión de Steam") \
    M(LoginPromptAccount, "Enter Steam account name:", "请输入 Steam 登录账号:", "Ingrese el nombre de la cuenta de Steam:") \
    M(LoginPromptPassword, "Enter Steam password (masked):", "请输入 Steam 密码 (输入已掩盖):", "Ingrese la contraseña de Steam (enmascarada):") \
    M(TokenExpiredTitle, "Login Token Expired", "登录凭据已过期", "Token de Inicio de Sesión Expirado") \
    M(TokenExpiredMsg, "Saved credentials for [{}] have expired or are no longer valid.", "账号 [{}] 的本地登录凭据已过期或失效。", "Las credenciales guardadas para [{}] han expirado o ya no son válidas.") \
    M(TokenExpiredPrompt, "Re-enter password to log in again now?", "是否立即重新输入密码登录该账号？", "¿Desea reingresar la contraseña para iniciar sesión ahora?") \
    M(ReloginTitle, "Re-login", "重新登录", "Reingresar") \
    M(ReloginPrompt, "Enter password for [{}]:", "请输入账号 [{}] 的密码:", "Ingrese la contraseña de [{}]:") \
    M(L3QuickInputHint, "(Type AppID & Enter, or Enter selected)", "(可输入数字回车，或按 Enter 提取选中)", "(Ingrese AppID o Enter para seleccionado)") \
    M(CsvExportTitle, "Export Games List Table", "导出游戏列表表格", "Exportar Lista de Juegos") \
    M(CsvExportMsg, "Export all {} games in this account to a CSV file?", "确定要将该账号下全部 {} 款游戏导出为 CSV 表格吗？", "¿Desea exportar los {} juegos de esta cuenta a un archivo CSV?") \
    M(CsvExportDetail, "Output file: gameslist-{}.csv", "输出文件: gameslist-{}.csv", "Archivo de salida: gameslist-{}.csv") \
    M(CsvExportSuccessTitle, "Export Successful", "导出成功", "Exportación Exitosa") \
    M(CsvExportSuccessMsg, "Table saved to: {}", "表格已保存至: {}", "Tabla guardada en: {}") \
    M(CsvExportSuccessDetail, "Encoded in UTF-8 with BOM; opens directly in Excel and spreadsheet apps.", "采用 UTF-8 BOM 编码，支持 Excel 或 WPS 直接双击打开查看。", "Codificado en UTF-8 con BOM; se puede abrir directamente en Excel u otros visores.") \
    M(BatchConfirmTitle, "Batch Extract Credentials", "批量提取凭据", "Extracción de Credenciales por Lotes") \
    M(BatchConfirmMsg, "Batch extract credentials for all {} games in this account?", "确定要批量提取当前账号下全部 {} 款游戏的凭据吗？", "¿Desea extraer por lotes las credenciales de los {} juegos de esta cuenta?") \
    M(BatchConfirmDetail, "Automatically extracts tickets, keys and Lua scripts (safely rate-limited).", "程序将按序自动提取票据、密钥与 Lua 脚本 (内置限速保护账号安全)", "Se extraerán automáticamente tickets, claves y scripts Lua (con límite seguro).") \
    M(CliExtractNoLicenseSwitch, "[INFO] Account [{}] has no license for AppID {} (no tickets/keys); trying next account...", "[INFO] 账号 [{}] 未拥有 AppID {} 的正版许可 (无票据或解密密钥)，自动尝试下一账号...", "[INFO] La cuenta [{}] no posee licencia para AppID {} (sin tickets/claves); probando siguiente cuenta...") \
    M(CliExtractLoginFailedSwitch, "[WARN] Account [{}] login failed; automatically trying next available account...", "[WARN] 账号 [{}] 登录失败，自动尝试下一个可用账号...", "[AVISO] Falló el inicio de sesión para [{}]; probando siguiente cuenta disponible...") \
    M(CliExtractLocalInjected, "[INFO] Environment set for AppID {}; preparing full extraction including eticket.bin.", "[INFO] 已为游戏 AppID {} 准备运行环境，将提取包括 eticket.bin 在内的完整凭据。", "[INFO] Entorno configurado para AppID {}; preparando extracción completa incluyendo eticket.bin.") \
    M(CliExtractLocalSafe, "[INFO] Target AppID {} not installed locally; safe offline extraction mode enabled.", "[INFO] 目标 AppID {} 未在本地安装，已启用离线安全提取模式。", "[INFO] El AppID {} no está instalado localmente; modo seguro habilitado.") \
    M(ConnectingNodeProgress, "Connecting to CM node ({}/{}) and logging in...", "正在连接 CM 节点 ({}/{}) 并登录...", "Conectando al nodo CM ({}/{}) e iniciando sesión...") \
    M(CliConnectingServer, "[NET] Connecting to Steam CM server ({}/{}): {}...", "[NET] 正在连接 Steam CM 服务器 ({}/{}): {}...", "[NET] Conectando al servidor CM de Steam ({}/{}): {}...") \
    M(CliLogonReady, "[OK] Steam CM logon ready! (SteamID: {})", "[OK] Steam CM 登录就绪！(SteamID: {})", "¡[OK] Inicio de sesión en Steam CM listo! (SteamID: {})") \
    M(CliExtractRequestTicket, "  -> Requesting AppOwnershipTicket from Steam CM...", "  -> 正在向 Steam CM 请求 AppOwnershipTicket...", "  -> Solicitando AppOwnershipTicket a Steam CM...") \
    M(CliExtractTicketGot, "     [OK] Retrieved ownership ticket ({} bytes)", "     [OK] 提取到所有权票据 ({} 字节)", "     [OK] Ticket de propiedad extraído ({} bytes)") \
    M(CliExtractDenuvoSession, "  -> Establishing dedicated session for encrypted ticket (Denuvo / DRM)...", "  -> 正在建立定向会话以提取加密票据 (Denuvo / 专用 DRM)...", "  -> Estableciendo sesión dirigida para ticket cifrado (Denuvo / DRM)...") \
    M(CliExtractEticketGot, "     [OK] Session activated, encrypted ticket retrieved ({} bytes)", "     [OK] 激活会话提取到加密票据 ({} 字节)", "     [OK] Sesión activada, ticket cifrado extraído ({} bytes)") \
    M(CliExtractQueryDepots, "  -> Querying depot decryption keys and licenses from Steam CM...", "  -> 正在向 Steam CM 查询 Depot 解密密钥与授权...", "  -> Consultando claves de descifrado y licencias de Depot en Steam CM...") \
    M(CliExtractPullManifests, "  -> Pulling official depot manifests (.manifest) from cloud...", "  -> 正在纯云端拉取官方清单文件 (.manifest)...", "  -> Descargando manifiestos oficiales (.manifest) desde la nube...") \
    M(CliExtractManifestsGot, "     [OK] Successfully pulled {} official manifest file(s)", "     [OK] 成功拉取 {} 个官方清单文件", "     [OK] Se descargaron {} archivo(s) de manifiesto oficial(es)") \
    M(CliExtractDepotKeysGot, "     [OK] Extracted {} depot decryption key(s)/manifest(s)", "     [OK] 提取到 {} 个 Depot 解密密钥/清单", "     [OK] Se extrajeron {} clave(s)/manifiesto(s) de depot") \
    M(CliExtractQueryAccessToken, "  -> Querying 64-bit PICS AccessToken...", "  -> 正在查询 64 位 PICS AccessToken...", "  -> Consultando AccessToken PICS de 64 bits...") \
    M(CliExtractAccessTokenGot, "     [OK] Retrieved PICS AccessToken", "     [OK] 提取到 PICS 访问令牌", "     [OK] Token de acceso PICS extraído") \
    M(OutExtractedDlcs, "[INFO] Extracted {} owned DLC(s):", "[INFO] 已提取 {} 个拥有的 DLC:", "[INFO] Se extrajeron {} DLC(s) adquirido(s):") \
    M(OutNoDlcs, "[INFO] No owned DLCs found for AppID {}.", "[INFO] 未检测到该游戏拥有的 DLC (AppID {})。", "[INFO] No se encontraron DLCs adquiridos para AppID {}.") \
    M(OutExtractedDepotKeys, "[INFO] Extracted {} depot decryption key(s):", "[INFO] 已提取 {} 个 Depot 解密密钥:", "[INFO] Se extrajeron {} clave(s) de descifrado de depot:") \
    M(OutNoDepotKeys, "[INFO] No cached depot decryption keys found in config.vdf for AppID {}.", "[INFO] 未在 config.vdf 中找到 AppID {} 缓存的 Depot 解密密钥。", "[INFO] No se encontraron claves de depot en config.vdf para AppID {}.") \
    M(OutDepotKeysTip, "[TIP] If this game requires depot keys, start installing/updating it once in Steam to cache them, then run extract_tickets again.", "[提示] 若该游戏需要 Depot 密钥，请在 Steam 中启动一次安装/更新以生成缓存，然后重新运行提取工具。", "[Consejo] Si el juego requiere claves de depot, inicie la instalación/actualización en Steam para almacenarlas en caché y vuelva a ejecutar extract_tickets.") \
    M(OutExtractedManifests, "[INFO] Extracted {} depot manifest file(s) (.manifest):", "[INFO] 已提取 {} 个清单文件 (.manifest):", "[INFO] Se extrajeron {} archivo(s) de manifiesto (.manifest):") \
    M(OutNoManifests, "[INFO] No cached .manifest files found in depotcache for AppID {}.", "[INFO] 未在 depotcache 中找到 AppID {} 缓存的清单文件 (.manifest)。", "[INFO] No se encontraron archivos .manifest en depotcache para AppID {}.") \
    M(OutExtractedTokens, "[INFO] Extracted {} access token(s):", "[INFO] 已提取 {} 个访问令牌 (AccessToken):", "[INFO] Se extrajeron {} token(s) de acceso (AccessToken):") \
    M(OutPublicProductTokenZero, "[INFO] This product is public and does not require an independent AccessToken (public mode token=0).", "[INFO] 该产品属于公开产品，无需独立 AccessToken，使用公开模式 token=0 即可。", "[INFO] Este producto es público y no requiere AccessToken independiente (token=0 en modo público).") \
    M(OutNoAccessTokenLocal, "[INFO] No non-zero access token found in appinfo.vdf for AppID {} (this game may not require an access token).", "[INFO] 未在 appinfo.vdf 中找到非零访问令牌 (该游戏可能无需 Access Token)。", "[INFO] No se encontró token de acceso en appinfo.vdf para AppID {} (puede no requerir token de acceso).") \
    M(OutConfigSaved, "[INFO] Ready-to-use Lua script saved to: {}", "[INFO] 配置文件已生成，保存至: {}", "[INFO] Script Lua listo para usar guardado en: {}") \
    M(OutWriteFileFailed, "[ERROR] Failed to write {}.", "[ERROR] 写入文件 {} 失败。", "[ERROR] Fallo al escribir {}.") \
    M(OutCreateDirFailed, "[ERROR] Failed to create directory {} ({}).", "[ERROR] 创建输出目录 {} 失败 ({})。", "[ERROR] Fallo al crear directorio {} ({}).") \
    M(ErrInvalidAppIdCli, "[ERROR] Invalid AppID: {}", "[ERROR] 无效的 AppID: {}", "[ERROR] AppID no válido: {}") \
    M(SessionNoSteamPath, "[WARN] Failed to find Steam install path in registry.", "[WARN] 未在注册表中找到 Steam 安装路径。", "[AVISO] No se encontró la ruta de instalación de Steam en el registro.") \
    M(SessionLoadClientFailed, "[WARN] Failed to load {} (GetLastError={}).", "[WARN] 加载 {} 失败 (GetLastError={})。", "[AVISO] Error al cargar {} (GetLastError={}).") \
    M(SessionNoCreateInterface, "[WARN] steamclient64.dll has no CreateInterface export.", "[WARN] steamclient64.dll 缺少 CreateInterface 导出。", "[AVISO] steamclient64.dll no exporta CreateInterface.") \
    M(SessionNoOwnershipTicket, "[INFO] Failed to retrieve ownership ticket for AppID {} (account may not own it or not cached locally).", "[INFO] 未能获取 AppID {} 的所有权票据 (账号可能未拥有或本地未缓存)。", "[INFO] No se pudo obtener el ticket de propiedad para AppID {} (puede no poseerlo o no estar en caché).") \
    M(SessionEncryptedTicketDenied, "[INFO] RequestEncryptedAppTicket returned AccessDenied (account does not own this app or lacks permission).", "[INFO] 请求 EncryptedAppTicket 被拒绝 (当前登录账号未拥有该游戏或无权获取其凭据)。", "[INFO] RequestEncryptedAppTicket denegado (la cuenta no posee esta app o carece de permisos).") \
    M(SessionEncryptedTicketEmpty, "[WARN] Encrypted app ticket is empty.", "[WARN] 加载的加密票据为空。", "[AVISO] El ticket de aplicación cifrado está vacío.") \
    M(SessionEncryptedTicketFailed, "[WARN] GetEncryptedAppTicket failed.", "[WARN] 获取 EncryptedAppTicket 数据失败。", "[AVISO] Falló GetEncryptedAppTicket.")

#define OST_I18N_ENUM_DEF(key, en, zh, es) key,

enum class MsgKey : size_t {
    OST_I18N_MESSAGES(OST_I18N_ENUM_DEF)
    COUNT
};

#undef OST_I18N_ENUM_DEF

inline constexpr size_t kMsgKeyCount = static_cast<size_t>(MsgKey::COUNT);

class I18n {
public:
    static Language DetectSystemLanguage() noexcept;
    static Language GetCurrentLanguage() noexcept;
    static void SetLanguage(Language lang) noexcept;
    static void InitLanguage() noexcept;
    [[nodiscard]] static std::string_view GetLanguageCode(Language lang = GetCurrentLanguage()) noexcept;
    [[nodiscard]] static const char* GetSteamLanguageCode(Language lang = GetCurrentLanguage()) noexcept;
    [[nodiscard]] static std::string_view Get(MsgKey key) noexcept;
};

[[nodiscard]] inline std::string_view TR(MsgKey key) noexcept {
    return I18n::Get(key);
}

template <typename... Args>
[[nodiscard]] inline std::string TR_FMT(MsgKey key, Args&&... args) {
    try {
        return std::vformat(TR(key), std::make_format_args(args...));
    } catch (const std::exception&) {
        return std::string{TR(key)};
    }
}

} // namespace OST::ExtractTickets
